// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat/protobuf/chat.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatUserV3 struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	VipLevel             int32    `protobuf:"varint,5,opt,name=vipLevel,proto3" json:"vipLevel,omitempty"`
	Power                int64    `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	ZoneId               string   `protobuf:"bytes,7,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	ZoneName             string   `protobuf:"bytes,8,opt,name=zoneName,proto3" json:"zoneName,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Extra                string   `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	ServerId             string   `protobuf:"bytes,11,opt,name=serverId,proto3" json:"serverId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatUserV3) Reset()         { *m = ChatUserV3{} }
func (m *ChatUserV3) String() string { return proto.CompactTextString(m) }
func (*ChatUserV3) ProtoMessage()    {}
func (*ChatUserV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a63f4f29c0a830b, []int{0}
}

func (m *ChatUserV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatUserV3.Unmarshal(m, b)
}
func (m *ChatUserV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatUserV3.Marshal(b, m, deterministic)
}
func (m *ChatUserV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatUserV3.Merge(m, src)
}
func (m *ChatUserV3) XXX_Size() int {
	return xxx_messageInfo_ChatUserV3.Size(m)
}
func (m *ChatUserV3) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatUserV3.DiscardUnknown(m)
}

var xxx_messageInfo_ChatUserV3 proto.InternalMessageInfo

func (m *ChatUserV3) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *ChatUserV3) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChatUserV3) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ChatUserV3) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ChatUserV3) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *ChatUserV3) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *ChatUserV3) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *ChatUserV3) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *ChatUserV3) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ChatUserV3) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *ChatUserV3) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

type ChatV3 struct {
	Channel              string      `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	From                 *ChatUserV3 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *ChatUserV3 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Content              string      `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Ip                   string      `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	CreatedAt            string      `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Extra                string      `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	Status               int32       `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string      `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChatV3) Reset()         { *m = ChatV3{} }
func (m *ChatV3) String() string { return proto.CompactTextString(m) }
func (*ChatV3) ProtoMessage()    {}
func (*ChatV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a63f4f29c0a830b, []int{1}
}

func (m *ChatV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatV3.Unmarshal(m, b)
}
func (m *ChatV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatV3.Marshal(b, m, deterministic)
}
func (m *ChatV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatV3.Merge(m, src)
}
func (m *ChatV3) XXX_Size() int {
	return xxx_messageInfo_ChatV3.Size(m)
}
func (m *ChatV3) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatV3.DiscardUnknown(m)
}

var xxx_messageInfo_ChatV3 proto.InternalMessageInfo

func (m *ChatV3) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ChatV3) GetFrom() *ChatUserV3 {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ChatV3) GetTo() *ChatUserV3 {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ChatV3) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ChatV3) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ChatV3) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ChatV3) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *ChatV3) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ChatV3) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatUserV3)(nil), "chat_protobuf.ChatUserV3")
	proto.RegisterType((*ChatV3)(nil), "chat_protobuf.ChatV3")
}

func init() { proto.RegisterFile("chat/protobuf/chat.proto", fileDescriptor_2a63f4f29c0a830b) }

var fileDescriptor_2a63f4f29c0a830b = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0xd3, 0x85, 0x16, 0x3a, 0x44, 0x0f, 0x1b, 0x43, 0x56, 0xe3, 0x81, 0x70, 0xc2, 0x83,
	0x90, 0xc8, 0x13, 0x18, 0x4f, 0x24, 0xc6, 0x43, 0x13, 0xb9, 0x9a, 0xa5, 0x1d, 0x42, 0x63, 0xe9,
	0x36, 0xdb, 0x05, 0xff, 0x1c, 0x7d, 0x1a, 0x1f, 0xd3, 0xcc, 0x6c, 0x0b, 0x72, 0xd0, 0x5b, 0x7f,
	0x7c, 0x3b, 0xf3, 0x31, 0x3f, 0x50, 0xe9, 0x46, 0xbb, 0x59, 0x65, 0x8d, 0x33, 0xab, 0xdd, 0x7a,
	0x46, 0x34, 0x65, 0x92, 0x67, 0xf4, 0xfd, 0xd2, 0x26, 0xe3, 0x6f, 0x01, 0xf0, 0xb0, 0xd1, 0xee,
	0xb9, 0x46, 0xbb, 0x9c, 0xcb, 0x2b, 0xe8, 0x57, 0x85, 0xfe, 0x40, 0xbb, 0xc8, 0x54, 0x30, 0x0a,
	0x26, 0x71, 0x72, 0x60, 0x39, 0x84, 0x68, 0x57, 0x73, 0x22, 0x38, 0x69, 0x88, 0x66, 0xca, 0x3c,
	0x7d, 0x2d, 0xf5, 0x16, 0x55, 0xc7, 0xcf, 0xb4, 0x2c, 0x2f, 0x20, 0x2c, 0x70, 0x8f, 0x85, 0xea,
	0x8e, 0x82, 0x49, 0x98, 0x78, 0xa0, 0x89, 0x7d, 0x5e, 0x3d, 0x72, 0x10, 0x72, 0x70, 0x60, 0x9a,
	0xa8, 0xcc, 0x1b, 0x5a, 0x15, 0x8d, 0x82, 0x49, 0x27, 0xf1, 0x40, 0xdd, 0x9f, 0xa6, 0xc4, 0x45,
	0xa6, 0x7a, 0xbe, 0xdb, 0x13, 0x6d, 0xa2, 0xaf, 0x27, 0xea, 0xee, 0xfb, 0xee, 0x96, 0xe5, 0x35,
	0xc4, 0xa9, 0x45, 0xed, 0x30, 0xbb, 0x77, 0x2a, 0xe6, 0xf0, 0xf8, 0x03, 0xf5, 0xe0, 0xbb, 0xb3,
	0x5a, 0x01, 0x27, 0x1e, 0x68, 0x5f, 0x8d, 0x76, 0xcf, 0x57, 0x0e, 0xfc, 0xbe, 0x96, 0xc7, 0x5f,
	0x02, 0x22, 0x52, 0xb5, 0x9c, 0x4b, 0x05, 0xbd, 0x74, 0xa3, 0xcb, 0x12, 0x8b, 0xc6, 0x52, 0x8b,
	0xf2, 0x16, 0xba, 0x6b, 0x6b, 0xb6, 0xac, 0x68, 0x70, 0x77, 0x39, 0x3d, 0xb1, 0x3d, 0x3d, 0x9a,
	0x4e, 0xf8, 0x99, 0xbc, 0x01, 0xe1, 0x0c, 0x5b, 0xfb, 0xf7, 0xb1, 0x70, 0x86, 0x3b, 0x4d, 0xe9,
	0xb0, 0x74, 0x2c, 0x93, 0x3a, 0x3d, 0xca, 0x73, 0x10, 0x79, 0xc5, 0x22, 0xe3, 0x44, 0xe4, 0xd5,
	0xe9, 0xe1, 0xd1, 0x9f, 0x87, 0xf7, 0x7e, 0x1f, 0x3e, 0x84, 0xa8, 0x76, 0xda, 0xed, 0x6a, 0xd6,
	0x18, 0x26, 0x0d, 0xf1, 0xee, 0xac, 0x71, 0x24, 0xf2, 0x6c, 0x15, 0xf1, 0xdf, 0x9b, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x10, 0xed, 0x54, 0x35, 0x61, 0x02, 0x00, 0x00,
}
